### ISSUE TITLE
Writing to the SQL database with GNU Radio

### ISSUE THREAD

**Issue by robellebor** [stwunsch/gr-sql#1]
why did u not write about that (Writing to the SQL database with GNU Radio) ????

**Comment by stwunsch** [comment]
What do you mean exactly? Btw this project is really old and not really supported. That's as well the reasons because it's not listed on [www.cgran.org](www.cgran.org).

**Comment by robellebor** [comment]
sorry , i dont really understand how to connect my gnuradio with mysql
